# Generated by Django 3.0.11 on 2021-03-21 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='people',
            name='relationship',
            field=models.CharField(choices=[('Aunt', 'Aunt'), ('Brother', 'Brother'), ('Cousin', 'Cousin'), ('Friend', 'Friend'), ('Mom', 'Mom'), ('Sister', 'Sister'), ('Unlce', 'Uncle'), ('Wife', 'Wife'), ('Self', 'Self')], default='Friend', max_length=10),
        ),
        migrations.AlterField(
            model_name='people',
            name='job_title',
            field=models.CharField(blank=True, max_length=254, verbose_name='Job title'),
        ),
    ]
