# Generated by Django 2.2.7 on 2019-12-24 18:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(help_text='Keep the name short, ideally one word.', max_length=80, unique=True, validators=[django.core.validators.RegexValidator(message="Letters, numbers and '&' only plus must start with a letter.", regex='^[\\w][a-zA-Z &]+$'), django.core.validators.MinLengthValidator(4)])),
                ('aliases', models.TextField(blank=True, help_text='What else is this known as or referred to as?', max_length=255, verbose_name='Also known as')),
                ('node_order_index', models.IntegerField(blank=True, default=0, editable=False)),
            ],
            options={
                'verbose_name': 'Taxonomy',
                'verbose_name_plural': 'Taxonomies',
            },
        ),
    ]
