# Generated by Django 3.2.9 on 2021-12-20 03:58

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('ratings', '0002_auto_20210327_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='TvIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='TvPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('description', models.TextField()),
                ('release_date', models.CharField(blank=True, max_length=10)),
                ('rating', models.IntegerField(blank=True)),
                ('poster', models.URLField(blank=True)),
                ('language', models.CharField(blank=True, max_length=2)),
                ('tmdb_id', models.IntegerField(default=None, unique=True)),
                ('watch_party', wagtail.core.fields.StreamField([('view_block', wagtail.core.blocks.StructBlock([('date', wagtail.core.blocks.DateBlock(required=False)), ('people', wagtail.core.blocks.StreamBlock([('person', wagtail.snippets.blocks.SnippetChooserBlock('page.People'))]))]))], blank=True, default='')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
