# Generated by Django 4.0.7 on 2022-09-13 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('ratings', '0004_alter_moviepage_watch_party_alter_tvpage_watch_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviepage',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Testing image pull from poster URLField', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
