# Generated by Django 4.0.7 on 2022-10-02 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0006_tvpage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviepage',
            name='release_date',
            field=models.DateField(),
        ),
    ]
