# Generated by Django 4.0.7 on 2022-10-02 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0007_alter_moviepage_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvpage',
            name='release_date',
            field=models.DateField(),
        ),
    ]
