# Generated by Django 4.2.1 on 2023-07-08 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0008_alter_tvpage_release_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieGenre',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(help_text='Max length 255 characters', max_length=255)),
            ],
        ),
    ]
