# Generated by Django 4.2.1 on 2023-07-08 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0009_moviegenre'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviepage',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ratings.moviegenre'),
        ),
    ]
