# Generated by Django 4.2.1 on 2023-07-08 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0010_moviepage_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviepage',
            name='genre',
        ),
        migrations.AddField(
            model_name='moviepage',
            name='genre',
            field=models.ManyToManyField(to='ratings.moviegenre'),
        ),
    ]
