# Generated by Django 4.2.1 on 2023-07-08 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0011_remove_moviepage_genre_moviepage_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Max Characters 100', max_length=100)),
            ],
        ),
    ]
