# Generated by Django 4.2.1 on 2023-07-09 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0015_credits_rename_tmdb_id_moviepage_movie_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviepage',
            name='people',
        ),
    ]
