# Generated by Django 4.2.1 on 2023-07-09 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0016_remove_moviepage_people'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credits',
            name='people',
        ),
        migrations.AddField(
            model_name='credits',
            name='cast',
            field=models.ManyToManyField(to='ratings.people'),
        ),
    ]
