# Generated by Django 4.2.1 on 2023-07-09 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0018_remove_credits_character_cast_alter_credits_cast'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Credits',
            new_name='Credit',
        ),
    ]
