# Generated by Django 4.2.1 on 2023-07-09 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0019_rename_credits_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='cast',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ratings.moviepage'),
        ),
        migrations.DeleteModel(
            name='Credit',
        ),
    ]
