# Generated by Django 4.2.1 on 2023-07-30 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0021_people_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TvGenre',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(help_text='Max length 255 characters', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TvCast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.TextField(help_text='Max length 100 characters', max_length=100)),
                ('cast_member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ratings.people')),
                ('tv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ratings.tvpage')),
            ],
        ),
        migrations.AddField(
            model_name='tvpage',
            name='genre',
            field=models.ManyToManyField(to='ratings.tvgenre'),
        ),
    ]
