# Generated by Django 5.0.6 on 2024-06-09 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0022_tvgenre_tvcast_tvpage_genre'),
        ('wagtailimages', '0026_delete_uploadedimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviepage',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Image pull from poster URL Field', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='tvpage',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Image pull from poster URL Field', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
