# Generated by Django 2.2.7 on 2019-12-24 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpeoplerelationship'),
        ('pages', '0002_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpeoplerelationship',
            name='people',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_blog_relationship', to='pages.People'),
        ),
    ]
