# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-08 03:35
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogindexpage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogindexpage',
            options={},
        ),
        migrations.AddField(
            model_name='blogindexpage',
            name='intro',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
    ]
