# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-08 17:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20161008_0335'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogindexpage',
            options={'verbose_name': 'Blog index'},
        ),
        migrations.RemoveField(
            model_name='blogindexpage',
            name='intro',
        ),
    ]
