# Generated by Django 2.2.7 on 2019-12-24 21:41

from django.db import migrations, models
import django.db.models.deletion
import taxonomy.models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0001_initial'),
        ('blog', '0004_auto_20191224_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='category',
            field=models.ForeignKey(blank=True, default='', limit_choices_to=taxonomy.models.Node.get_blog_categories, null=True, on_delete=django.db.models.deletion.PROTECT, to='taxonomy.Node'),
        ),
    ]
