# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20161014_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='flickr_photoset_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
