# Generated by Django 4.1.3 on 2022-12-18 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('blog', '0005_alter_blogpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogindexpage',
            name='hero_image',
            field=models.ForeignKey(blank=True, help_text='Landscape mode only;                   horizontal width between 1000px and 3000px.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='hero_image',
            field=models.ForeignKey(blank=True, help_text='Landscape mode only;                   horizontal width between 1000px and 3000px.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
