# Generated by Django 2.2.9 on 2020-01-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogpage_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='flickr_photoset_id',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
