# Generated by Django 4.2.1 on 2023-05-29 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_blogpage_body'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
