# Generated by Django 5.1.6 on 2025-03-30 23:09

import django.db.models.deletion
import taxonomy.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_blogpage_body'),
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='category',
            field=models.ForeignKey(blank=True, limit_choices_to=taxonomy.models.Node.get_blog_categories, null=True, on_delete=django.db.models.deletion.PROTECT, to='taxonomy.node'),
        ),
    ]
