# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 21:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_col_md_12'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='col_md_12',
            new_name='Bootstrap12',
        ),
        migrations.AlterModelOptions(
            name='bootstrap12',
            options={'verbose_name': 'Bootstrap 12 Column'},
        ),
    ]
