# Generated by Django 3.0.11 on 2020-12-21 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20201221_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='view_date',
        ),
        migrations.AddField(
            model_name='movieviewdate',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movie.Movie'),
        ),
    ]
