# Generated by Django 2.2.9 on 2020-06-02 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_remove_movie_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='creation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
