# Generated by Django 3.0.11 on 2020-12-21 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20201221_1203'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['title']},
        ),
        migrations.AlterField(
            model_name='movieviewdate',
            name='date',
            field=models.DateField(),
        ),
    ]
