# Generated by Django 3.0.6 on 2020-06-03 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_remove_movie_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='creation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
