# Generated by Django 3.0.6 on 2020-06-03 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_movie_creation_date'),
        ('movie', '0002_movie_slug'),
    ]

    operations = [
    ]
