# Generated by Django 3.0.11 on 2020-12-21 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_auto_20201221_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='creation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
