# Generated by Django 3.0.6 on 2020-06-03 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_merge_20200603_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='creation_date',
        ),
    ]
