# Generated by Django 3.0.11 on 2021-03-16 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_remove_movie_creation_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MovieViewDate',
        ),
    ]
