# Generated by Django 3.0.11 on 2021-03-21 23:26

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_delete_movieviewdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='view_date',
            field=wagtail.core.fields.StreamField([('view_date', wagtail.core.blocks.StructBlock([('date', wagtail.core.blocks.DateTimeBlock(required=False))]))], blank=True, default=''),
        ),
    ]
