# Generated by Django 3.0.13 on 2021-03-27 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_movie_view_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
