# Generated by Django 4.2.7 on 2023-12-28 20:59

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('microblog', '0002_alter_microblogpage_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='microblogpage',
            name='date_published',
        ),
        migrations.AlterField(
            model_name='microblogpage',
            name='body',
            field=wagtail.fields.StreamField([('paragraph', wagtail.blocks.RichTextBlock(features=['h2', 'h3', 'bold', 'italic', 'link', 'code'], icon='pilcrow', template='blocks/paragraph_block.html')), ('date_published', wagtail.blocks.DateTimeBlock(blank=True, null=True))], use_json_field=True),
        ),
    ]
