# Generated by Django 4.2.7 on 2023-12-29 21:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('microblog', '0003_remove_microblogpage_date_published_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='microblogpage',
            name='date_published',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
