# Generated by Django 4.2.7 on 2023-12-29 21:35

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('microblog', '0004_microblogpage_date_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='microblogpage',
            name='content',
            field=wagtail.fields.RichTextField(default=''),
            preserve_default=False,
        ),
    ]
