# Generated by Django 4.2.7 on 2023-12-30 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microblog', '0005_microblogpage_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='microblogpage',
            name='body',
        ),
    ]
