# Generated by Django 4.2.7 on 2023-12-30 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microblog', '0006_remove_microblogpage_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='microblogpage',
            old_name='content',
            new_name='body',
        ),
    ]
