# Generated by Django 5.1.6 on 2025-03-30 23:08

import django.db.models.deletion
import taxonomy.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microblog', '0007_rename_content_microblogpage_body'),
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microblogpage',
            name='category',
            field=models.ForeignKey(blank=True, limit_choices_to=taxonomy.models.Node.get_micro_blog_categories, null=True, on_delete=django.db.models.deletion.PROTECT, to='taxonomy.node'),
        ),
    ]
